apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    app: simple-application
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: simple-application
  template:
    metadata:
      labels:
        app: simple-application
    spec:
      containers:
      - name: simple-application
        image: srijavignesh/tomcat-application:latest
        ports:
        - containerPort: 8080
